# Generated by Django 4.1 on 2022-08-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_dislikes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
